services:
  mysql:
    image: mysql:8.0
    container_name: products-db-container
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: products
    ports:
      - "3310:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - product-demo-network

volumes:
  mysql_data:

networks:
  product-demo-network:
    external: true
